version: "3.9"
services:
  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    env_file: .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_HOST=http://172.16.15.112:11434
    depends_on: [qdrant, redis]
    volumes:
      - ./api:/app/api
      - ./ingestion:/app/ingestion
      - ./embedding:/app/embedding
      - ./retriever:/app/retriever
      - ./llm:/app/llm

  worker:
    build: .
    command: celery -A api.main.celery_app worker -l info
    env_file: .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_HOST=http://172.16.15.112:11434
    depends_on: [qdrant, redis]
    volumes:
      - ./api:/app/api
      - ./ingestion:/app/ingestion
      - ./embedding:/app/embedding
      - ./retriever:/app/retriever
      - ./llm:/app/llm

  qdrant:
    image: qdrant/qdrant:v1.9.3
    ports: ["6333:6333"]
    volumes: ["qdrant_data:/qdrant/storage"]
    environment:
      - QDRANT__LOG_LEVEL=INFO

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes: ["redis_data:/data"]

  streamlit:
    build: .
    command: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port 8501
    ports: ["8501:8501"]
    environment:
      - API_BASE_URL=http://api:8000
    depends_on: [api]
    volumes:
      - ./streamlit_app.py:/app/streamlit_app.py

volumes:
  qdrant_data:
  redis_data: